# Generated by Django 2.0 on 2017-12-16 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '5. Addition',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_present_days', models.IntegerField(default=0)),
                ('total_days', models.IntegerField(default=30)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '2. Attendance',
            },
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('attendance_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Attendance')),
            ],
            options={
                'verbose_name_plural': '4. Compensation',
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '8. Deduction',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('salary', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '1. Employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspended', models.BooleanField(default=False)),
                ('married', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], default='Unmarried', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '0. Employee Statuses',
            },
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(default='Not mentioned.', max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('sum_total', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee')),
            ],
            options={
                'verbose_name_plural': '3. Incentive',
            },
        ),
        migrations.CreateModel(
            name='MonthlySheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': '9. Monthly Sheets',
            },
        ),
        migrations.CreateModel(
            name='PayRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(default='Not mentioned.', max_length=255)),
                ('payment', models.PositiveIntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Attendance')),
                ('monthly_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.MonthlySheet')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee')),
            ],
            options={
                'verbose_name_plural': ' PayRoll',
            },
        ),
        migrations.CreateModel(
            name='ProvidentFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('sum_total', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee')),
            ],
            options={
                'verbose_name_plural': '7. ProvidentFund',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('percent', models.FloatField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee')),
            ],
            options={
                'verbose_name_plural': '6. Tax',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeStatus'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='provident_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.ProvidentFund'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='tax_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Tax'),
        ),
        migrations.AddField(
            model_name='compensation',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee'),
        ),
        migrations.AddField(
            model_name='addition',
            name='compenstation_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Compensation'),
        ),
        migrations.AddField(
            model_name='addition',
            name='incentive_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Incentive'),
        ),
        migrations.AddField(
            model_name='addition',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee'),
        ),
    ]
