# Generated by Django 2.0 on 2017-12-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='estimated_days',
        ),
    ]
