# Generated by Django 2.0 on 2017-12-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_payroll_estimated_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='salary',
        ),
    ]
