# Generated by Django 2.0 on 2017-12-15 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20171215_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='note',
        ),
        migrations.AddField(
            model_name='payroll',
            name='cause',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
